## Programming Assignment 9

This week you will submit your programming assignment as a .ipynb notebook that contains an exploration webscraping

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

## Pandas Exploration:

#### There are 1000 movies listed on this website:

First 200 movies:
https://www.boxofficemojo.com/chart/top_lifetime_gross/?area=XWW

Next 200 movies:
https://www.boxofficemojo.com/chart/top_lifetime_gross/?area=XWW&offset=200

##### Can you figure out the pattern to get the next one?

Your goal is to access and analyze this data.

### 1 Get the Data:

Use pandas.read_html() and a for loop to get all of the top 1000 movies of all time in terms of gross income.

Construct a single data frame with this information in it.

HINT - notice a patten in the website names for the first 200 vs the second 200, use that pattern to get each of the data sets. 

-----------------------------------------------

HINT - You will need to write code that combines the Data Frames. Here is some sample code. Given data frame 1 and 2 we can combine them using the concat function.

    df = pd.concat([df1, df2]).reset_index(drop=True)
    
I am happy to help you construc the for loop to combine all these data frames

In [3]:
dfs = []

for i in range(0, 1000, 200):
    url = "https://www.boxofficemojo.com/chart/top_lifetime_gross/?area=XWW"
    
    if i != 0:
        url += f"&offset={i}"
    
    dfs.append(pd.read_html(url)[0])

movies = pd.concat(dfs).reset_index(drop=True)

print(movies)

     Rank                     Title  Lifetime Gross  Year
0       1                    Avatar  $2,923,710,708  2009
1       2         Avengers: Endgame  $2,799,439,100  2019
2       3  Avatar: The Way of Water  $2,334,484,620  2022
3       4                   Titanic  $2,264,812,968  1997
4       5                  Ne Zha 2  $2,260,176,370  2025
..    ...                       ...             ...   ...
995   996           The Other Woman    $196,710,396  2014
996   997                  Stargate    $196,567,262  1994
997   998                   Beowulf    $196,393,745  2007
998   999                   The Vow    $196,114,570  2012
999  1000          Anger Management    $195,745,823  2003

[1000 rows x 4 columns]

In [8]:
#1 
movies.columns

Index(['Rank', 'Title', 'Lifetime Gross', 'Year'], dtype='object')

### 2. Do Something with the Data

1. Explain what each of the columns contains - both what the data means and what data type it is.
2. What is the range of years in the data set? Are there any missing years? What years are represented? Are there any strange gaps or single years?

4. Write a function that given a year with display a data frame for the movies of that year OR tell the user there are no movies found for that year. NOTE: this must be a function!

5. Write code that will find which year had the most top grossing movies. Display the data frame with just this year of movies.

In [10]:
#1 
movies.dtypes

Rank               int64
Title             object
Lifetime Gross    object
Year               int64
dtype: object

1. Rank contains highest grossing movies in the all time box office movies with 1 being the highest grossing. The rank column is an integer. TItle is the name of the moive and it is a string. The Lifetime Gross column is the total money earned in dollars. This column is a string currently because it has the dollar sign and it has commas. I think I will convert this to a float for further analysis. Year is the year the movie was released and it is an integer.
2. The data has years ranging from a min of 1939 and a max of 2026 giving us a total of 88 years covered. We do have quite a few missing years of 31, but mostly the years near 1940s through the 1960s are missing. This to me suggests that the highest grossing movies are coming from more recent years rather than prior decades.
4. The year with the highest grossing movies was 2017. The highest grossing movie from 2017 was a Star wars movie.

In [16]:
#2 
min_year = movies['Year'].min()
min_year

1939

In [15]:
#2
max_year = movies['Year'].max()
max_year

2026

In [21]:
#2
len(movies['Year'].unique())

57

In [18]:
#2
range_year = max_year - min_year +1
range_year

88

In [24]:
#2
missing = range_year - len(movies['Year'].unique())
missing

31

In [25]:
#3
def get_movies_by_year(year):
    df = movies[movies['Year'] == year]
    
    if df.empty:
        print("Movies for that year missing.")
    else:
        return df

In [31]:
get_movies_by_year(2017)

,Rank,Title,Lifetime Gross,Year
23,24,Star Wars: Episode VIII - The Last Jedi,1.334408e+09,2017
26,27,Beauty and the Beast,1.266116e+09,2017
28,29,The Fate of the Furious,1.236009e+09,2017
52,53,Despicable Me 3,1.034800e+09,2017
66,67,Jumanji: Welcome to the Jungle,9.625446e+08,2017
86,87,Spider-Man: Homecoming,8.809782e+08,2017
91,92,Wolf Warrior 2,8.703254e+08,2017
95,96,Guardians of the Galaxy Vol. 2,8.637642e+08,2017
99,100,Thor: Ragnarok,8.553018e+08,2017
104,105,Wonder Woman,8.239707e+08,2017
105,106,Coco,8.232858e+08,2017
115,116,Pirates of the Caribbean: Dead Men Tell No Tales,7.959223e+08,2017
148,149,It,7.197660e+08,2017
172,173,Justice League,6.613270e+08,2017
193,194,Logan,6.191805e+08,2017
202,203,Transformers: The Last Knight,6.054252e+08,2017
220,221,Kong: Skull Island,5.686528e+08,2017
231,232,Dunkirk,5.491367e+08,2017
251,252,The Boss Baby,5.279659e+08,2017
277,278,War for the Planet of the Apes,4.907198e+08,2017
300,301,The Greatest Showman,4.718767e+08,2017
372,373,Kingsman: The Golden Circle,4.109027e+08,2017
374,375,The Mummy,4.092316e+08,2017
415,416,Cars 3,3.839307e+08,2017
418,419,Fifty Shades Darker,3.815458e+08,2017
479,480,Murder on the Orient Express,3.527941e+08,2017
500,501,xXx: Return of Xander Cage,3.461183e+08,2017
517,518,Never Say Die,3.345309e+08,2017
559,560,Wonder,3.150259e+08,2017
565,566,The Lego Batman Movie,3.123367e+08,2017
574,575,The Ex-File 3: Return of the Exes,3.075924e+08,2017
581,582,Annabelle: Creation,3.065922e+08,2017
615,616,Ferdinand,2.960692e+08,2017
628,629,Paddington 2,2.901325e+08,2017
647,648,Split,2.784544e+08,2017
649,650,Blade Runner 2049,2.779376e+08,2017
709,710,Kung Fu Yoga,2.577539e+08,2017
719,720,Baahubali 2: The Conclusion,2.541584e+08,2017
744,745,Journey to the West: The Demons Strike Back,2.475852e+08,2017
773,774,Alien: Covenant,2.408922e+08,2017
826,827,Youth,2.270913e+08,2017
827,828,Baby Driver,2.269451e+08,2017
834,835,Valerian and the City of a Thousand Planets,2.259733e+08,2017
848,849,Geostorm,2.219002e+08,2017
868,869,The Emoji Movie,2.177766e+08,2017
952,953,A Dog's Purpose,2.050358e+08,2017
991,992,Smurfs: The Lost Village,1.971835e+08,2017

In [29]:
#4 
year_counts = movies['Year'].value_counts()
top_year = year_counts.idxmax()
print(top_year)

2017

In [32]:
# Cleaning
movies['Lifetime Gross'] = (
    movies['Lifetime Gross']
    .replace('[\$,]', '', regex=True)
    .astype(float)
)

### 4. Keep Exploring:

Go to the website: https://www.boxofficemojo.com/

Find another pace with interesting tables on it. Then do the following:

1. Use Pandas to get the data
2. Explain what data is in the data frame (or frames)
3. Come up with at least 2 questions that you will answer using code you write.
4. Answer your questions. 

Try to write your code so it gives nice useful outputs. For example print statements that tell the user what they are looking at and comments (or markdown) that tell the user what you are doing and why it is interesting.

In [33]:
#1
url = "https://www.boxofficemojo.com/franchise/?ref_=bo_lnav_hm_shrt"
tables = pd.read_html(url)

franchises_df = tables[0]
franchises_df.head()

,Franchise,Total,Releases,#1 Release,Lifetime Gross
0,Marvel Cinematic Universe,"$13,104,471,816",44,Avengers: Endgame,"$858,373,000"
1,Star Wars,"$5,137,465,429",25,Star Wars: Episode VII - The Force Awakens,"$936,662,225"
2,Disney Live Action Reimaginings,"$3,493,794,115",17,The Lion King,"$543,638,043"
3,Spider-Man,"$3,319,377,679",22,Spider-Man: No Way Home,"$804,793,477"
4,DC Extended Universe,"$3,135,867,379",21,Wonder Woman,"$412,563,408"

2. This data is from the franchise table from the box office mojo page. It has 315 elements and 5 columns. The columns include Franchise(the name of the movie franchise which is a string), Total(Total box office gross of the franchise in the U.S. and Canada which is a strign), Releases(Number of films in the franchise which is an integer), #1 Release(Highest grossing movies from the franchise which is a string), and Lifetime Gross(The box office earnings of the top release which is a string right now).

In [34]:
#2 
franchises_df.shape

(315, 5)

In [35]:
#2
franchises_df.dtypes

Franchise         object
Total             object
Releases           int64
#1 Release        object
Lifetime Gross    object
dtype: object

2 questions we are going to try to answer using this data:
1. Which franchise has the most releases?
2. Which franchise has the highest total domestic gross?

In [36]:
# Question 1
max_releases = franchises_df.loc[franchises_df['Releases'].idxmax()]

print("Franchise with the most releases:")
print(max_releases)

Franchise with the most releases:
Franchise         Marvel Cinematic Universe
Total                       $13,104,471,816
Releases                                 44
#1 Release                Avengers: Endgame
Lifetime Gross                 $858,373,000
Name: 0, dtype: object

In [37]:
# Question 2
franchises_df['Total'] = (
    franchises_df['Total']
    .replace('[\$,]', '', regex=True)
    .astype(float)
)

max_gross_franchise = franchises_df.loc[franchises_df['Total'].idxmax()]

print("Franchise with highest total gross:")
print(max_gross_franchise)

Franchise with highest total gross:
Franchise         Marvel Cinematic Universe
Total                         13104471816.0
Releases                                 44
#1 Release                Avengers: Endgame
Lifetime Gross                 $858,373,000
Name: 0, dtype: object

In [42]:
print(f"Most Releases: {max_releases['Franchise']} ({max_releases['Releases']} films)")
print(f"Highest Total Gross: {max_gross_franchise['Franchise']} (${max_gross_franchise['Total']:,.0f})")

Most Releases: Marvel Cinematic Universe (44 films)
Highest Total Gross: Marvel Cinematic Universe ($13,104,471,816)

To answer these questions I started by using pandas to read in the Box office Mojo franchise table into a dataframe. I looked at the columns and their types to see what kind of questions I could answer. Then after cleaning the data so the total column was a number I was able to compare the total box office grossing for each franchise to find the highest grossing franchise.